name: action-test_testing
on:
  push :
    branches: [ testing ]
  pull_request: 
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: kanstant/action-test@main
      
